name: Automated API tests using Newman CLI
on: workflow_dispatch

jobs:
  test-API:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create dir
        run: mkdir TestArtifact

      - uses: actions/setup-node@v3
      - name: Install Node
        with:
          node-version: '20'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra

      - name: Run Tests
        run: newman run "APIAUTOMATION.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export TestArtifact/htmlreport.html

      - name: Upload the reports
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: TestArtifact
