name: Run Postman Tests with Node Version 20

on:
  push:
    branches: [main]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Print Context Variables
        run: |
          echo "Server URL: ${{ github.server_url }}"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create testArtifacts folder
        run: mkdir testArtifacts

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra



      - name: Run Postman Tests
        run: newman run APIAUTOMATION.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: testArtifacts

      - name: Send Email Notification
        uses: actions/send-mail@v3
        with:
          to: someswararao.m@gmail.com
          subject: Postman Test Results
          body: "Your Postman tests have completed. You can view the results here: ${{ github.server_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"