name: Run Postman Tests with Node Version 20

on:
  push:
    branches: [main]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Create testArtifacts folder
        run: mkdir testArtifacts

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra



      - name: Run Postman Tests
        run: newman run APIAUTOMATION.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html