name: Node and Newman Job

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Replace with your desired Node.js version
     - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra

      - name: Run Tests
        run: newman run "APIAUTOMATION.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export TestArtifact/htmlreport.html

      - uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: TestArtifact
